version: "3.9"

services:
  api:
    build: .
    container_name: hungsql-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
    command: uvicorn hungsql.api.main:app --host 0.0.0.0 --port 8000 --reload