services:
  dbcsv-server:
    build:
      context: ./dbcsv/server
      dockerfile: Dockerfile
    volumes:
      - ./dbcsv/server:/app
      - ./db:/app/db
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  dbcsv-client:
    build:
      context: ./dbcsv/client/
      dockerfile: Dockerfile
    volumes:
      - ./dbcsv/client:/app
    working_dir: /app
    command: python -m dbapi2.connection
